//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Angry Bird/ThrowableInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ThrowableInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ThrowableInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ThrowableInputActions"",
    ""maps"": [
        {
            ""name"": ""Throwable"",
            ""id"": ""a54aed18-fc17-49fd-85c1-0c55eac48e06"",
            ""actions"": [
                {
                    ""name"": ""Throw"",
                    ""type"": ""Value"",
                    ""id"": ""b5553c07-a5a2-4363-8a95-d029fcd7f5c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Ablilty"",
                    ""type"": ""Button"",
                    ""id"": ""3a12fbf9-9840-40d2-8ee8-c171e219514c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fc68b806-e43a-4874-8504-4760d6d51e4f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10c159c0-608d-4a0b-8c49-1302e3ddabcb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ablilty"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Throwable
        m_Throwable = asset.FindActionMap("Throwable", throwIfNotFound: true);
        m_Throwable_Throw = m_Throwable.FindAction("Throw", throwIfNotFound: true);
        m_Throwable_Ablilty = m_Throwable.FindAction("Ablilty", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Throwable
    private readonly InputActionMap m_Throwable;
    private List<IThrowableActions> m_ThrowableActionsCallbackInterfaces = new List<IThrowableActions>();
    private readonly InputAction m_Throwable_Throw;
    private readonly InputAction m_Throwable_Ablilty;
    public struct ThrowableActions
    {
        private @ThrowableInputActions m_Wrapper;
        public ThrowableActions(@ThrowableInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Throw => m_Wrapper.m_Throwable_Throw;
        public InputAction @Ablilty => m_Wrapper.m_Throwable_Ablilty;
        public InputActionMap Get() { return m_Wrapper.m_Throwable; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ThrowableActions set) { return set.Get(); }
        public void AddCallbacks(IThrowableActions instance)
        {
            if (instance == null || m_Wrapper.m_ThrowableActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ThrowableActionsCallbackInterfaces.Add(instance);
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @Ablilty.started += instance.OnAblilty;
            @Ablilty.performed += instance.OnAblilty;
            @Ablilty.canceled += instance.OnAblilty;
        }

        private void UnregisterCallbacks(IThrowableActions instance)
        {
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @Ablilty.started -= instance.OnAblilty;
            @Ablilty.performed -= instance.OnAblilty;
            @Ablilty.canceled -= instance.OnAblilty;
        }

        public void RemoveCallbacks(IThrowableActions instance)
        {
            if (m_Wrapper.m_ThrowableActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IThrowableActions instance)
        {
            foreach (var item in m_Wrapper.m_ThrowableActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ThrowableActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ThrowableActions @Throwable => new ThrowableActions(this);
    public interface IThrowableActions
    {
        void OnThrow(InputAction.CallbackContext context);
        void OnAblilty(InputAction.CallbackContext context);
    }
}
